name: Diff pdf on Push

on:
  push:
    branches: [ "main" ] # 適切なブランチ名に変更してください

env:
  REVIEW_CONFIG_FILE: 'config.yml'

jobs:
  diff-pdf:
    runs-on: ubuntu-latest
    container:
      image: vvakame/review:5.3

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 100

      - name: Build PDF
        run: |
          REVIEW_CONFIG_FILE=${{ env.REVIEW_CONFIG_FILE }} rake pdf
          mv ./*.pdf ../output.pdf
        working-directory: how-to-git/.github/workflows/articles  # 適切なディレクトリに変更してください

      - uses: actions/upload-artifact@v2
        with:
          name: Output PDF
          path: output.pdf
