name: Diff pdf

on: [push]
jobs:
  diff-pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: nowsprinting/diff-pdf-action@v1
        with:
          file1: base.pdf
          file2: head.pdf
          options: --output-diff=diff.pdf
          suppress-diff-error: true
